
spring.datasource.url=jdbc:postgresql://localhost:5433/servio
spring.datasource.username=mariaclara_fo
spring.datasource.password=Clara.951

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect